name: Terraform CI

on:
  push:
    branches:
      - main

  pull_request:
    branches:
      - main

jobs:
  validate:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.13.0

      - name: Verify Terraform Installation
        run: terraform version
      
      - name: Check Terraform Formatting
        run: terraform fmt -check -recursive
      - name: Show Repository Structure
        run: |
          pwd
          ls -la
      - name: Terraform Init 
        working-directory: workspace-infra/environments/dev
        run: terraform init

      - name: Terraform Validate
        working-directory: workspace-infra/environments/dev
        run: terraform validate

      - name: Terraform Plan
        working-directory: workspace-infra/environments/dev
        run: terraform plan